# Change these first
owner: gabrielroot # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: JOY
    url: http://joy.rockfellerbrasil.com.br
  - name: JOY_DEV
    url: http://joydf.rockfellerbrasil.com.br

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  logoUrl: https://github.com/gabrielroot/uptime/blob/master/assets/brand.png
  introTitle: "**Hello!** Por aqui, você acompanha o status de funcionamento de nossos serviços."
  introMessage: A atualização desses status são realizadas automaticamente, a cada 5 minutos!
  navbar:
   - title: Status
     href: https://$OWNER.github.io/$REPO/
   - title: GitHub
     href: https://github.com/$OWNER/$REPO
  baseUrl: /uptime
  name: DFranquias services
  theme: dark #light|night|ocean
assignees:
  - Alex-Bruno
  - gabrielroot
  - Joao-V-A-Braga
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration